stages:
  - test
  - deploy

variables:
  GITLAB_MAKE: "make -f .gitlab.mk"
  IMAGE_PERF: "${CI_REGISTRY}/${CI_PROJECT_PATH}/perf/ubuntu-bionic:perf_master"
  IMAGE_PERF_BUILT: "${CI_REGISTRY}/${CI_PROJECT_PATH}/perf/ubuntu-bionic:perf_${CI_COMMIT_SHORT_SHA}"

perf_bootstrap:
  stage: test
  tags:
    - perf
  script:
    - ${GITLAB_MAKE} docker_perf_bootstrap

perf_tpcc:
  image: ${IMAGE_PERF_BUILT}
  stage: deploy
  tags:
    - docker_perf
  script:
    - ${GITLAB_MAKE} perf_tpcc

perf_sysbench:
  image: ${IMAGE_PERF_BUILT}
  stage: deploy
  tags:
    - docker_perf
  variables:
    TIME: 100
  script:
    - ${GITLAB_MAKE} perf_sysbench
